class Company_model {
  final int id;
  final String name;
  final String position;
  final String image;
  final String description;

  Company_model({
    required this.id,
    required this.name,
    required this.position,
    required this.image,
    required this.description,
  });

  static List<Company_model> CompanyModels() => [
        Company_model(
          id: 0,
          name: 'Owais Ahmed Khan',
          position: 'CEO',
          image: 'assets/team/owais.jpg',
          description:
              "A chief executive officer (CEO) is the highest-ranking executive of a firm. CEOs act as the company's public face and make major corporate decisions.",
        ),
        Company_model(
          id: 1,
          name: 'Abdul Rafay Khan',
          position: 'COO',
          image: 'assets/team/ark.jpeg',
          description: "Our Expert",
        ),
        Company_model(
          id: 2,
          name: 'Huzaifa Ali, (CTO)',
          position: 'CTO',
          image: 'assets/team/huzaifa.jpeg',
          description: "React Developer",
        ),
        Company_model(
          id: 3,
          name: 'Mishal Riasat',
          position: 'Developer',
          image: 'assets/team/mishalriasat.jpeg',
          description: "Developer",
        ),
        Company_model(
          id: 4,
          name: 'Muhammad Saeed',
          position: 'Developer',
          image: 'assets/team/saeed.jpeg',
          description: "Developer",
        ),
        Company_model(
          id: 5,
          name: 'Fatima alvi',
          position: 'Developer',
          image: 'assets/team/fatima.jpg',
          description: "Developer",
        ),
        Company_model(
          id: 6,
          name: 'Sami Ahmad',
          position: 'Developer',
          image: 'assets/team/samiahmed.png',
          description: "Developer",
        ),
        Company_model(
          id: 7,
          name: 'M Furqan Latif',
          position: 'Web Developer',
          image: 'assets/team/mfurqan.jpg',
          description: "Web Developer",
        ),
        Company_model(
          id: 8,
          name: 'Aiman Atif',
          position: 'Developer',
          image: "assets/team/aimandev.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 9,
          name: 'Sameen Fatime',
          position: 'Developer',
          image: "assets/team/sameen.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 10,
          name: 'Soha Fatime',
          position: 'Developer',
          image: "assets/team/soha.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 11,
          name: 'Muhammad Nadeem',
          position: 'Developer',
          image: "assets/team/nadeem.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 12,
          name: 'Rashid Fareed',
          position: 'Developer',
          image: "assets/team/rashid.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 13,
          name: 'Muhammad Saad',
          position: 'Developer',
          image: "assets/team/saad.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 14,
          name: 'Waqas Mughal',
          position: 'Developer',
          image: "assets/team/waqasmughal.jpg",
          description: "Developer",
        ),
        Company_model(
          id: 15,
          name: 'Abdullah Asif',
          position: 'Developer',
          image: "assets/team/abdullahdeveloper.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 16,
          name: 'Talha Nasir',
          position: 'Developer',
          image: "assets/team/talha.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 17,
          name: 'Kumail Raza',
          position: 'Developer',
          image: "assets/team/kumailraza.jpg",
          description: "Developer",
        ),
        Company_model(
          id: 18,
          name: 'Ubaid Shah Nawaz',
          position: 'Developer',
          image: "assets/team/ubaidshah.jpg",
          description: "Developer",
        ),
        Company_model(
          id: 19,
          name: 'Usman Sohaib',
          position: 'Graphic Designer',
          image: "assets/team/usmansohaib.jpeg",
          description: "Graphic Designer",
        ),
        Company_model(
          id: 20,
          name: 'Tehseen Ullah',
          position: 'Developer',
          image: "assets/team/tehseenullah.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 21,
          name: 'Asad',
          position: 'Developer',
          image: "assets/team/asaddev.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 22,
          name: 'Hussnain Zafar',
          position: 'Developer',
          image: "assets/team/husnain.jpg",
          description: "Developer",
        ),
        Company_model(
          id: 23,
          name: 'Abubakar',
          position: 'Developer',
          image: "assets/team/abubakr.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 24,
          name: 'Malik Usman',
          position: 'Developer',
          image: "assets/team/malik.PNG",
          description: "Developer",
        ),
        Company_model(
          id: 25,
          name: 'Waleed Butt',
          position: 'Developer',
          image: "assets/team/waleed.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 26,
          name: 'Faiq Dogar',
          position: 'Developer',
          image: "assets/team/faiq.jpeg",
          description: "Developer",
        ),
        Company_model(
          id: 27,
          name: '',
          position: '',
          image: "",
          description: "",
        ),
      ];
}
