// ignore: camel_case_types
import 'package:get/get_state_manager/src/simple/get_controllers.dart';

class model {
  final int id;
  final String name;
  final String image;
  final String description;
  final String Shortdescription;
  final double rate;

  model({
    required this.id,
    required this.name,
    required this.image,
    required this.description,
    required this.Shortdescription,
    required this.rate,
  });

  static List<model> getCoursesData() => [
        model(
            id: 0,
            name: 'Graphic design',
            image: 'assets/course/Graphics.PNG',
            description:
                'Graphic design is the art, profession and academic discipline whose activity consists in projecting visual communications intended to transmit specific messages to social groups, with specific objectives.The role of the graphic designer in the communication process is that of encoder or interpreter of the message. They work on the interpretation, ordering and presentation of visual messages.',
            Shortdescription:
                'Graphic design is the art,\n profession and academic \ndiscipline.',
            rate: 2000),
        model(
          id: 1,
          name: 'Angular',
          image: 'assets/course/Angular.PNG',
          description:
              'Angular is a TypeScript-based open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations. Angular is a complete rewrite from the same team that built AngularJS',
          Shortdescription:
              'Angular is a TypeScript-based open-source web application framework led by the Angular Team at Google.',
          rate: 2000,
        ),
        model(
          id: 2,
          name: 'Java',
          image: 'assets/course/java.PNG',
          description:
              'In our Java & Spring Framework Developer course students will learn to develop Java applications and services using Spring Framework and related technologies such as Spring Boot, Spring JPA / Hibernate & Spring Cloud. The course starts with introduction to Java & OOP in Java and moves on to Spring Framework, Inversion of Control (IoC), Dependency Injection (DI) and Java Beans. The course also covers enterprise level web application development using Spring MVC and database programming using Hibernate. The course further covers Webservices & Microservices development using Spring Boot & Spring Cloud which can be used as backend for modern web and mobile applications.',
          Shortdescription:
              'In our Java & Spring Framework Developer\n course students will learn to develop Java applications.',
          rate: 2000,
        ),
        model(
          id: 3,
          name: ' JavaScript',
          image: 'assets/course/Javascript.PNG',
          description:
              'JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities. JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.',
          Shortdescription:
              'JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages.',
          rate: 2000,
        ),
        model(
          id: 4,
          name: 'WordPress',
          image: 'assets/course/wordpress.PNG',
          description:
              'WordPress powers nearly one-third of the world’s websites, from small personal blogs to the complex sites of major corporations such as Sony, Time Inc., the New York Post, and NBC. WordPress is only one of the site builders and content management systems users can download and install for free, but it has unique features that make it the most popular content management system in use today.',
          Shortdescription:
              'WordPress powers nearly one-third of the world’s websites, from small personal blogs to the complex sites of major corporations.',
          rate: 2000,
        ),
        model(
            id: 5,
            name: 'App Development',
            image: 'assets/course/App_Development.PNG',
            description:
                'React Native is an open-source mobile application framework created by Facebook, Inc. It is used to develop applications for Android, Android TV, iOS, macOS, tvOS, Web, Windows and UWP by enabling developers to use React\'s framework along with native platform capabilities.',
            Shortdescription:
                'React Native is an open-source mobile application framework created by Facebook, Inc.',
            rate: 2000),
        model(
          id: 6,
          name: 'React JS',
          image: 'assets/course/React.PNG',
          description:
              'The Complete React JS Course - Basics to Advance this course is a complete guide for React JS. Here, you will learn all the concepts required for becoming a front-end React JS developer. If you are new to web development or a professional developer who\'s creating websites with plain old javascript or jQuery, this is your time to learn React JS and take your web development skills to the next level and impress your recruiter or clients',
          Shortdescription:
              'The Complete React JS Course - Basics to Advance this course is a complete guide for React JS.',
          rate: 2000,
        ),
        model(
          id: 7,
          name: 'ASP Net',
          image: 'assets/course/ASP_Net.PNG',
          description:
              'This extensive project driven course covers n-tier web application development using Microsoft. NET Framework / .NET Core, Visual Studio 2019 and SQL Server 2017. It includes object oriented programming using C#, web development using HTML5, CSS3 and Bootstrap 4; Interactive and rich UI development using JavaScript, jQuery and jQuery UI; Server side programming using ASP .NET Core MVC, Web API and C#; Database programming using ADO .NET Entity Framework, LINQ and SQL Server 2017.',
          Shortdescription:
              'This extensive project driven course covers n-tier web application development using Microsoft.',
          rate: 2000,
        ),
        model(
          id: 8,
          name: ' Fronted Development',
          image: 'assets/course/Frontend.PNG',
          description:
              'In this project based course you will learn to develop interactive and responsive websites and front-end web development of a enterprise application. It includes HTML5 and CSS3 for creating beautiful web pages; JavaScript & jQuery for more interactive and rich Web UI; BootStrap for developing responsive and elegant websites; AJAX & JSON for consuming REST Services. The course also covers essentials of Angular for front-end web development.',
          Shortdescription:
              'In this project based course you will learn to develop interactive and responsive websites and front-end web development.',
          rate: 2000,
        ),
        model(
          id: 9,
          name: 'WordPress',
          image: 'assets/course/Python.PNG',
          description:
              'Python is an interpreted high-level general-purpose programming language. Python\'s design philosophy emphasizes code readability with its notable use of significant indentation. Its language constructs as well as its object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.',
          Shortdescription:
              'Python is an interpreted high-level general-purpose programming language.',
          rate: 2000,
        ),
        model(
            id: 10,
            name: 'Node JS',
            image: 'assets/course/NodeJS.PNG',
            description:
                'Node.js is an open-source and cross-platform JavaScript runtime environment. It is a popular tool for almost any kind of project! Node.js runs the V8 JavaScript engine, the core of Google Chrome, outside of the browser. This allows Node.js to be very performant. A Node.js app runs in a single process, without creating a new thread for every request. Node.js provides a set of asynchronous I/O primitives in its standard library that prevent JavaScript code from blocking and generally, libraries in Node.js are written using non-blocking paradigms, making blocking behavior the exception rather than the norm.When Node.js performs an I/O operation, like reading from the network, accessing a database or the filesystem, instead of blocking the thread and wasting CPU cycles waiting, Node.js will resume the operations when the response comes back.',
            Shortdescription:
                'Node.js is an open-source and cross-platform JavaScript runtime environment.',
            rate: 2000),
        model(
          id: 11,
          name: 'Block Chain',
          image: 'assets/course/Blockchain.PNG',
          description:
              'Blockchain is a shared, immutable ledger that facilitates the process of recording transactions and tracking assets in a business network. An asset can be tangible (a house, car, cash, land) or intangible (intellectual property, patents, copyrights, branding). Virtually anything of value can be tracked and traded on a blockchain network, reducing risk and cutting costs for all involved.',
          Shortdescription:
              'Blockchain is a shared, immutable ledger that facilitates the process of recording transactions.',
          rate: 2000,
        ),
        model(
          id: 12,
          name: 'Vue JS',
          image: 'assets/course/Vue_JS.PNG',
          description:
              'Vue.js is a JavaScript framework for building user interfaces (UIs) and single-page applications (SPAs). Just like the best of them, Vue.js is open-source. It utilizes a model-view-viewmodel (MVVM) architectural pattern. Designed by Evan You and released in 2014, the framework is a direct response to You’s time spent working with AngularJS at Google. You wanted to extract the bits and pieces he liked from AngularJS and create an entirely new but notably lightweight framework. The MVVM architecture allows for the business logic, or model, to be distinguished from the graphical UI, or view. In effect, the distinction provides an intentionally intuitive pattern for front-end and back-end developers to work with. The view model is the structure keeping such concerns separate, acting as a liaison. Further, Vue.js has a core library that focuses only on the view layer.',
          Shortdescription:
              'Vue.js is a JavaScript framework for building user interfaces (UIs) and single-page applications (SPAs).',
          rate: 2000,
        ),
        model(
          id: 13,
          name: '',
          image: '',
          description: ' ',
          Shortdescription: '',
          rate: 2000,
        ),
      ];
}
